version: '3.8'
services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    ports:
      - "5173:5173"
      - "5000:5000"
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskmaster_db
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
